<script lang="ts">
    // This component renders nothing, but it is useful for enforcing Tailwind CSS classes to be generated.

    interface Props {
        classList?: string[];
    }

    const { classList }: Props = $props();

    // this a workaround for tailwind 4 not supporting the safelist option
    // each class in this list will be generated by tailwind, even if it is not used in the code, but
    // it can parse only full class names and cannot handle code-generated class names like ['xs', 'cs'].map(x => `${x}:class`)

    /* prettier-ignore */
    const defaultSafeList = [
        ['bg-surface', 'bg-container', 'bg-sub-container'],
        ['bg-on-surface', 'bg-on-container', 'bg-on-sub-container'],
        ['hover:bg-surface', 'hover:bg-container', 'hover:bg-sub-container'],
        ['hover:bg-on-surface', 'hover:bg-on-container', 'hover:bg-on-sub-container'],

        ['bg-primary', 'bg-secondary', 'bg-info', 'bg-warning', 'bg-danger', 'bg-success'],
        ['bg-primary-1', 'bg-secondary-1', 'bg-info-1', 'bg-warning-1', 'bg-danger-1', 'bg-success-1'],
        ['bg-primary-2', 'bg-secondary-2', 'bg-info-2', 'bg-warning-2', 'bg-danger-2', 'bg-success-2'],
        ['bg-on-primary', 'bg-on-secondary', 'bg-on-info', 'bg-on-warning', 'bg-on-danger', 'bg-on-success'],
        ['hover:bg-primary', 'hover:bg-secondary', 'hover:bg-info', 'hover:bg-warning', 'hover:bg-danger', 'hover:bg-success' ],

        ['shadow-on-surface', 'shadow-on-container', 'shadow-on-sub-container'],
        ['shadow-on-primary', 'shadow-on-secondary', 'shadow-on-info', 'shadow-on-warning', 'shadow-on-danger', 'shadow-on-success'],

        ['text-surface', 'text-container', 'text-sub-container'],
        ['text-on-surface', 'text-on-container', 'text-on-sub-container'],
        ['text-primary', 'text-secondary', 'text-info', 'text-warning', 'text-danger', 'text-success'],
        ['text-primary-1', 'text-secondary-1', 'text-info-1', 'text-warning-1', 'text-danger-1', 'text-success-1'],
        ['text-primary-2', 'text-secondary-2', 'text-info-2', 'text-warning-2', 'text-danger-2', 'text-success-2'],
        ['text-on-primary', 'text-on-secondary', 'text-on-info', 'text-on-warning', 'text-on-danger', 'text-on-success'],
        ['text-on-primary-1', 'text-on-secondary-1', 'text-on-info-1', 'text-on-warning-1', 'text-on-danger-1', 'text-on-success-1'],
        ['text-on-primary-2', 'text-on-secondary-2', 'text-on-info-2', 'text-on-warning-2', 'text-on-danger-2', 'text-on-success-2'],

        ['placeholder:text-surface', 'placeholder:text-container', 'placeholder:text-sub-container'],
        ['placeholder:text-on-surface', 'placeholder:text-on-container', 'placeholder:text-on-sub-container'],
        ['placeholder:text-primary', 'placeholder:text-secondary', 'placeholder:text-info', 'placeholder:text-warning', 'placeholder:text-danger', 'placeholder:text-success'],
        ['placeholder:text-primary-1', 'placeholder:text-secondary-1', 'placeholder:text-info-1', 'placeholder:text-warning-1', 'placeholder:text-danger-1', 'placeholder:text-success-1'],
        ['placeholder:text-primary-2', 'placeholder:text-secondary-2', 'placeholder:text-info-2', 'placeholder:text-warning-2', 'placeholder:text-danger-2', 'placeholder:text-success-2'],
        ['placeholder:text-on-primary', 'placeholder:text-on-secondary', 'placeholder:text-on-info', 'placeholder:text-on-warning', 'placeholder:text-on-danger', 'placeholder:text-on-success'],

        ['hover:ring-inset', 'hover:ring-outset'],
        ['hover:ring-0', 'hover:ring-1', 'hover:ring-2', 'hover:ring-3', 'hover:ring-4'],
        ['hover:ring-primary', 'hover:ring-secondary', 'hover:ring-info', 'hover:ring-warning', 'hover:ring-danger', 'hover:ring-success'],
        ['hover:ring-on-primary', 'hover:ring-on-secondary', 'hover:ring-on-info', 'hover:ring-on-warning', 'hover:ring-on-danger', 'hover:ring-on-success'],
        ['hover:ring-primary-1', 'hover:ring-secondary-1', 'hover:ring-info-1', 'hover:ring-warning-1', 'hover:ring-danger-1', 'hover:ring-success-1'],
        ['hover:ring-primary-2', 'hover:ring-secondary-2', 'hover:ring-info-2', 'hover:ring-warning-2', 'hover:ring-danger-2', 'hover:ring-success-2'],

        ['active:ring-inset', 'active:ring-outset'],
        ['active:ring-0', 'active:ring-1', 'active:ring-2', 'active:ring-3', 'active:ring-4'],
        ['active:ring-primary', 'active:ring-secondary', 'active:ring-info', 'active:ring-warning', 'active:ring-danger', 'active:ring-success'],
        ['active:ring-on-primary', 'active:ring-on-secondary', 'active:ring-on-info', 'active:ring-on-warning', 'active:ring-on-danger', 'active:ring-on-success'],
        ['active:ring-primary-1', 'active:ring-secondary-1', 'active:ring-info-1', 'active:ring-warning-1', 'active:ring-danger-1', 'active:ring-success-1'],
        ['active:ring-primary-2', 'active:ring-secondary-2', 'active:ring-info-2', 'active:ring-warning-2', 'active:ring-danger-2', 'active:ring-success-2'],

        ['focus:ring-inset', 'focus:ring-outset'],
        ['focus:ring-0', 'focus:ring-1', 'focus:ring-2', 'focus:ring-3', 'focus:ring-4'],
        ['focus:ring-primary', 'focus:ring-secondary', 'focus:ring-info', 'focus:ring-warning', 'focus:ring-danger', 'focus:ring-success'],
        ['focus:ring-on-primary', 'focus:ring-on-secondary', 'focus:ring-on-info', 'focus:ring-on-warning', 'focus:ring-on-danger', 'focus:ring-on-success'],
        ['focus:ring-primary-1', 'focus:ring-secondary-1', 'focus:ring-info-1', 'focus:ring-warning-1', 'focus:ring-danger-1', 'focus:ring-success-1'],
        ['focus:ring-primary-2', 'focus:ring-secondary-2', 'focus:ring-info-2', 'focus:ring-warning-2', 'focus:ring-danger-2', 'focus:ring-success-2'],

        ['group-focus:ring-inset', 'group-focus:ring-outset'],
        ['group-focus:ring-0', 'group-focus:ring-1', 'group-focus:ring-2', 'group-focus:ring-3', 'group-focus:ring-4'],
        ['group-focus:ring-primary', 'group-focus:ring-secondary', 'group-focus:ring-info', 'group-focus:ring-warning', 'group-focus:ring-danger', 'group-focus:ring-success'],
        ['group-focus:ring-on-primary', 'group-focus:ring-on-secondary', 'group-focus:ring-on-info', 'group-focus:ring-on-warning', 'group-focus:ring-on-danger', 'group-focus:ring-on-success'],
        ['group-focus:ring-primary-1', 'group-focus:ring-secondary-1', 'group-focus:ring-info-1', 'group-focus:ring-warning-1', 'group-focus:ring-danger-1', 'group-focus:ring-success-1'],
        ['group-focus:ring-primary-2', 'group-focus:ring-secondary-2', 'group-focus:ring-info-2', 'group-focus:ring-warning-2', 'group-focus:ring-danger-2', 'group-focus:ring-success-2'],

        ['focus-visible:ring-inset', 'focus-visible:ring-outset'],
        ['focus-visible:ring-0', 'focus-visible:ring-1', 'focus-visible:ring-2', 'focus-visible:ring-3', 'focus-visible:ring-4'],
        ['focus-visible:ring-primary', 'focus-visible:ring-secondary', 'focus-visible:ring-info', 'focus-visible:ring-warning', 'focus-visible:ring-danger', 'focus-visible:ring-success'],
        ['focus-visible:ring-on-primary', 'focus-visible:ring-on-secondary', 'focus-visible:ring-on-info', 'focus-visible:ring-on-warning', 'focus-visible:ring-on-danger', 'focus-visible:ring-on-success'],
        ['focus-visible:ring-primary-1', 'focus-visible:ring-secondary-1', 'focus-visible:ring-info-1', 'focus-visible:ring-warning-1', 'focus-visible:ring-danger-1', 'focus-visible:ring-success-1'],
        ['focus-visible:ring-primary-2', 'focus-visible:ring-secondary-2', 'focus-visible:ring-info-2', 'focus-visible:ring-warning-2', 'focus-visible:ring-danger-2', 'focus-visible:ring-success-2'],

        ['group-focus-visible:ring-inset', 'group-focus-visible:ring-outset'],
        ['group-focus-visible:ring-0', 'group-focus-visible:ring-1', 'group-focus-visible:ring-2', 'group-focus-visible:ring-3', 'group-focus-visible:ring-4'],
        ['group-focus-visible:ring-primary', 'group-focus-visible:ring-secondary', 'group-focus-visible:ring-info', 'group-focus-visible:ring-warning', 'group-focus-visible:ring-danger', 'group-focus-visible:ring-success'],
        ['group-focus-visible:ring-on-primary', 'group-focus-visible:ring-on-secondary', 'group-focus-visible:ring-on-info', 'group-focus-visible:ring-on-warning', 'group-focus-visible:ring-on-danger', 'group-focus-visible:ring-on-success'],
        ['group-focus-visible:ring-primary-1', 'group-focus-visible:ring-secondary-1', 'group-focus-visible:ring-info-1', 'group-focus-visible:ring-warning-1', 'group-focus-visible:ring-danger-1', 'group-focus-visible:ring-success-1'],
        ['group-focus-visible:ring-primary-2', 'group-focus-visible:ring-secondary-2', 'group-focus-visible:ring-info-2', 'group-focus-visible:ring-warning-2', 'group-focus-visible:ring-danger-2', 'group-focus-visible:ring-success-2'],

        ['border-surface', 'border-container', 'border-sub-container'],
        ['border-on-surface', 'border-on-container', 'border-on-sub-container'],
        ['border-primary', 'border-secondary', 'border-info', 'border-warning', 'border-danger', 'border-success'],
        ['border-primary-1', 'border-secondary-1', 'border-info-1', 'border-warning-1', 'border-danger-1', 'border-success-1'],
        ['border-primary-2', 'border-secondary-2', 'border-info-2', 'border-warning-2', 'border-danger-2', 'border-success-2'],
        ['border-on-primary', 'border-on-secondary', 'border-on-info', 'border-on-warning', 'border-on-danger', 'border-on-success'],

        ['fill-surface', 'fill-container', 'fill-sub-container'],
        ['fill-on-surface', 'fill-on-container', 'fill-on-sub-container'],
        ['fill-primary', 'fill-secondary', 'fill-info', 'fill-warning', 'fill-danger', 'fill-success'],
        ['fill-primary-1', 'fill-secondary-1', 'fill-info-1', 'fill-warning-1', 'fill-danger-1', 'fill-success-1'],
        ['fill-primary-2', 'fill-secondary-2', 'fill-info-2', 'fill-warning-2', 'fill-danger-2', 'fill-success-2'],
        ['fill-on-primary', 'fill-on-secondary', 'fill-on-info', 'fill-on-warning', 'fill-on-danger', 'fill-on-success'],

        ['stroke-surface', 'stroke-container', 'stroke-sub-container'],
        ['stroke-on-surface', 'stroke-on-container', 'stroke-on-sub-container'],
        ['stroke-primary', 'stroke-secondary', 'stroke-info', 'stroke-warning', 'stroke-danger', 'stroke-success'],
        ['stroke-primary-1', 'stroke-secondary-1', 'stroke-info-1', 'stroke-warning-1', 'stroke-danger-1', 'stroke-success-1'],
        ['stroke-primary-2', 'stroke-secondary-2', 'stroke-info-2', 'stroke-warning-2', 'stroke-danger-2', 'stroke-success-2'],
        ['stroke-on-primary', 'stroke-on-secondary', 'stroke-on-info', 'stroke-on-warning', 'stroke-on-danger', 'stroke-on-success'],

        ['bg-data-1', 'bg-data-2', 'bg-data-3', 'bg-data-4', 'bg-data-5', 'bg-data-6', 'bg-data-7', 'bg-data-8'],
        ['bg-data-1-1', 'bg-data-2-1', 'bg-data-3-1', 'bg-data-4-1', 'bg-data-5-1', 'bg-data-6-1', 'bg-data-7-1', 'bg-data-8-1'],
        ['bg-data-1-2', 'bg-data-2-2', 'bg-data-3-2', 'bg-data-4-2', 'bg-data-5-2', 'bg-data-6-2', 'bg-data-7-2', 'bg-data-8-2'],
        ['text-on-data-1', 'text-on-data-2', 'text-on-data-3', 'text-on-data-4', 'text-on-data-5', 'text-on-data-6', 'text-on-data-7', 'text-on-data-8'],
        ['text-data-1', 'text-data-2', 'text-data-3', 'text-data-4', 'text-data-5', 'text-data-6', 'text-data-7', 'text-data-8'],
        ['fill-data-1', 'fill-data-2', 'fill-data-3', 'fill-data-4', 'fill-data-5', 'fill-data-6', 'fill-data-7', 'fill-data-8'],
        ['stroke-data-1', 'stroke-data-2', 'stroke-data-3', 'stroke-data-4', 'stroke-data-5', 'stroke-data-6', 'stroke-data-7', 'stroke-data-8'],

        ['brightness-highlight', 'hover:brightness-highlight'],
        ['backdrop-brightness-highlight', 'hover:backdrop-brightness-highlight'],

        ['justify-start', 'justify-end', 'justify-center', 'justify-between', 'justify-around', 'justify-evenly'],
        ['xs:justify-start', 'xs:justify-end', 'xs:justify-center', 'xs:justify-between', 'xs:justify-around', 'xs:justify-evenly'],
        ['sm:justify-start', 'sm:justify-end', 'sm:justify-center', 'sm:justify-between', 'sm:justify-around', 'sm:justify-evenly'],
        ['md:justify-start', 'md:justify-end', 'md:justify-center', 'md:justify-between', 'md:justify-around', 'md:justify-evenly'],
        ['lg:justify-start', 'lg:justify-end', 'lg:justify-center', 'lg:justify-between', 'lg:justify-around', 'lg:justify-evenly'],
        ['xl:justify-start', 'xl:justify-end', 'xl:justify-center', 'xl:justify-between', 'xl:justify-around', 'xl:justify-evenly'],

        ['items-start', 'items-end', 'items-center', 'items-baseline', 'items-stretch'],
        ['xs:items-start', 'xs:items-end', 'xs:items-center', 'xs:items-baseline', 'xs:items-stretch'],
        ['sm:items-start', 'sm:items-end', 'sm:items-center', 'sm:items-baseline', 'sm:items-stretch'],
        ['md:items-start', 'md:items-end', 'md:items-center', 'md:items-baseline', 'md:items-stretch'],
        ['lg:items-start', 'lg:items-end', 'lg:items-center', 'lg:items-baseline', 'lg:items-stretch'],
        ['xl:items-start', 'xl:items-end', 'xl:items-center', 'xl:items-baseline', 'xl:items-stretch'],

        ['text-xs', 'text-sm', 'text-md', 'text-lg'],
        ['icon-xs', 'icon-sm', 'icon-md', 'icon-lg'],

        ['gap-0', 'gap-1', 'gap-2', 'gap-3', 'gap-4', 'gap-5', 'gap-6', 'gap-7', 'gap-8', 'gap-9', 'gap-10', 'gap-11', 'gap-12'],
        ['xs:gap-0', 'xs:gap-1', 'xs:gap-2', 'xs:gap-3', 'xs:gap-4', 'xs:gap-5', 'xs:gap-6', 'xs:gap-7', 'xs:gap-8', 'xs:gap-9', 'xs:gap-10', 'xs:gap-11', 'xs:gap-12'],
        ['sm:gap-0', 'sm:gap-1', 'sm:gap-2', 'sm:gap-3', 'sm:gap-4', 'sm:gap-5', 'sm:gap-6', 'sm:gap-7', 'sm:gap-8', 'sm:gap-9', 'sm:gap-10', 'sm:gap-11', 'sm:gap-12'],
        ['md:gap-0', 'md:gap-1', 'md:gap-2', 'md:gap-3', 'md:gap-4', 'md:gap-5', 'md:gap-6', 'md:gap-7', 'md:gap-8', 'md:gap-9', 'md:gap-10', 'md:gap-11', 'md:gap-12'],
        ['lg:gap-0', 'lg:gap-1', 'lg:gap-2', 'lg:gap-3', 'lg:gap-4', 'lg:gap-5', 'lg:gap-6', 'lg:gap-7', 'lg:gap-8', 'lg:gap-9', 'lg:gap-10', 'lg:gap-11', 'lg:gap-12'],
        ['xl:gap-0', 'xl:gap-1', 'xl:gap-2', 'xl:gap-3', 'xl:gap-4', 'xl:gap-5', 'xl:gap-6', 'xl:gap-7', 'xl:gap-8', 'xl:gap-9', 'xl:gap-10', 'xl:gap-11', 'xl:gap-12'],

        ['gap-x-0', 'gap-x-1', 'gap-x-2', 'gap-x-3', 'gap-x-4', 'gap-x-5', 'gap-x-6', 'gap-x-7', 'gap-x-8', 'gap-x-9', 'gap-x-10', 'gap-x-11', 'gap-x-12'],
        ['xs:gap-x-0', 'xs:gap-x-1', 'xs:gap-x-2', 'xs:gap-x-3', 'xs:gap-x-4', 'xs:gap-x-5', 'xs:gap-x-6', 'xs:gap-x-7', 'xs:gap-x-8', 'xs:gap-x-9', 'xs:gap-x-10', 'xs:gap-x-11', 'xs:gap-x-12'],
        ['sm:gap-x-0', 'sm:gap-x-1', 'sm:gap-x-2', 'sm:gap-x-3', 'sm:gap-x-4', 'sm:gap-x-5', 'sm:gap-x-6', 'sm:gap-x-7', 'sm:gap-x-8', 'sm:gap-x-9', 'sm:gap-x-10', 'sm:gap-x-11', 'sm:gap-x-12'],
        ['md:gap-x-0', 'md:gap-x-1', 'md:gap-x-2', 'md:gap-x-3', 'md:gap-x-4', 'md:gap-x-5', 'md:gap-x-6', 'md:gap-x-7', 'md:gap-x-8', 'md:gap-x-9', 'md:gap-x-10', 'md:gap-x-11', 'md:gap-x-12'],
        ['lg:gap-x-0', 'lg:gap-x-1', 'lg:gap-x-2', 'lg:gap-x-3', 'lg:gap-x-4', 'lg:gap-x-5', 'lg:gap-x-6', 'lg:gap-x-7', 'lg:gap-x-8', 'lg:gap-x-9', 'lg:gap-x-10', 'lg:gap-x-11', 'lg:gap-x-12'],
        ['xl:gap-x-0', 'xl:gap-x-1', 'xl:gap-x-2', 'xl:gap-x-3', 'xl:gap-x-4', 'xl:gap-x-5', 'xl:gap-x-6', 'xl:gap-x-7', 'xl:gap-x-8', 'xl:gap-x-9', 'xl:gap-x-10', 'xl:gap-x-11', 'xl:gap-x-12'],

        ['gap-y-0', 'gap-y-1', 'gap-y-2', 'gap-y-3', 'gap-y-4', 'gap-y-5', 'gap-y-6', 'gap-y-7', 'gap-y-8', 'gap-y-9', 'gap-y-10', 'gap-y-11', 'gap-y-12'],
        ['xs:gap-y-0', 'xs:gap-y-1', 'xs:gap-y-2', 'xs:gap-y-3', 'xs:gap-y-4', 'xs:gap-y-5', 'xs:gap-y-6', 'xs:gap-y-7', 'xs:gap-y-8', 'xs:gap-y-9', 'xs:gap-y-10', 'xs:gap-y-11', 'xs:gap-y-12'],
        ['sm:gap-y-0', 'sm:gap-y-1', 'sm:gap-y-2', 'sm:gap-y-3', 'sm:gap-y-4', 'sm:gap-y-5', 'sm:gap-y-6', 'sm:gap-y-7', 'sm:gap-y-8', 'sm:gap-y-9', 'sm:gap-y-10', 'sm:gap-y-11', 'sm:gap-y-12'],
        ['md:gap-y-0', 'md:gap-y-1', 'md:gap-y-2', 'md:gap-y-3', 'md:gap-y-4', 'md:gap-y-5', 'md:gap-y-6', 'md:gap-y-7', 'md:gap-y-8', 'md:gap-y-9', 'md:gap-y-10', 'md:gap-y-11', 'md:gap-y-12'],
        ['lg:gap-y-0', 'lg:gap-y-1', 'lg:gap-y-2', 'lg:gap-y-3', 'lg:gap-y-4', 'lg:gap-y-5', 'lg:gap-y-6', 'lg:gap-y-7', 'lg:gap-y-8', 'lg:gap-y-9', 'lg:gap-y-10', 'lg:gap-y-11', 'lg:gap-y-12'],
        ['xl:gap-y-0', 'xl:gap-y-1', 'xl:gap-y-2', 'xl:gap-y-3', 'xl:gap-y-4', 'xl:gap-y-5', 'xl:gap-y-6', 'xl:gap-y-7', 'xl:gap-y-8', 'xl:gap-y-9', 'xl:gap-y-10', 'xl:gap-y-11', 'xl:gap-y-12'],

        ['p-0', 'p-0.5', 'p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-7', 'p-8', 'p-9', 'p-10', 'p-11', 'p-12', 'p-14', 'p-16', 'p-20', 'p-24', 'p-28', 'p-32', 'p-36', 'p-40', 'p-44', 'p-48', 'p-52', 'p-56'],
        ['xs:p-0', 'xs:p-0.5', 'xs:p-1', 'xs:p-2', 'xs:p-3', 'xs:p-4', 'xs:p-5', 'xs:p-6', 'xs:p-7', 'xs:p-8', 'xs:p-9', 'xs:p-10', 'xs:p-11', 'xs:p-12', 'xs:p-14', 'xs:p-16', 'xs:p-20', 'xs:p-24', 'xs:p-28', 'xs:p-32', 'xs:p-36', 'xs:p-40', 'xs:p-44', 'xs:p-48', 'xs:p-52', 'xs:p-56'],
        ['sm:p-0', 'sm:p-0.5', 'sm:p-1', 'sm:p-2', 'sm:p-3', 'sm:p-4', 'sm:p-5', 'sm:p-6', 'sm:p-7', 'sm:p-8', 'sm:p-9', 'sm:p-10', 'sm:p-11', 'sm:p-12', 'sm:p-14', 'sm:p-16', 'sm:p-20', 'sm:p-24', 'sm:p-28', 'sm:p-32', 'sm:p-36', 'sm:p-40', 'sm:p-44', 'sm:p-48', 'sm:p-52', 'sm:p-56'],
        ['md:p-0', 'md:p-0.5', 'md:p-1', 'md:p-2', 'md:p-3', 'md:p-4', 'md:p-5', 'md:p-6', 'md:p-7', 'md:p-8', 'md:p-9', 'md:p-10', 'md:p-11', 'md:p-12', 'md:p-14', 'md:p-16', 'md:p-20', 'md:p-24', 'md:p-28', 'md:p-32', 'md:p-36', 'md:p-40', 'md:p-44', 'md:p-48', 'md:p-52', 'md:p-56'],
        ['lg:p-0', 'lg:p-0.5', 'lg:p-1', 'lg:p-2', 'lg:p-3', 'lg:p-4', 'lg:p-5', 'lg:p-6', 'lg:p-7', 'lg:p-8', 'lg:p-9', 'lg:p-10', 'lg:p-11', 'lg:p-12', 'lg:p-14', 'lg:p-16', 'lg:p-20', 'lg:p-24', 'lg:p-28', 'lg:p-32', 'lg:p-36', 'lg:p-40', 'lg:p-44', 'lg:p-48', 'lg:p-52', 'lg:p-56'],
        ['xl:p-0', 'xl:p-0.5', 'xl:p-1', 'xl:p-2', 'xl:p-3', 'xl:p-4', 'xl:p-5', 'xl:p-6', 'xl:p-7', 'xl:p-8', 'xl:p-9', 'xl:p-10', 'xl:p-11', 'xl:p-12', 'xl:p-14', 'xl:p-16', 'xl:p-20', 'xl:p-24', 'xl:p-28', 'xl:p-32', 'xl:p-36', 'xl:p-40', 'xl:p-44', 'xl:p-48', 'xl:p-52', 'xl:p-56'],

        ['px-0', 'px-0.5', 'px-1', 'px-2', 'px-3', 'px-4', 'px-5', 'px-6', 'px-7', 'px-8', 'px-9', 'px-10', 'px-11', 'px-12', 'px-14', 'px-16', 'px-20', 'px-24', 'px-28', 'px-32', 'px-36', 'px-40', 'px-44', 'px-48', 'px-52', 'px-56'],
        ['xs:px-0', 'xs:px-0.5', 'xs:px-1', 'xs:px-2', 'xs:px-3', 'xs:px-4', 'xs:px-5', 'xs:px-6', 'xs:px-7', 'xs:px-8', 'xs:px-9', 'xs:px-10', 'xs:px-11', 'xs:px-12', 'xs:px-14', 'xs:px-16', 'xs:px-20', 'xs:px-24', 'xs:px-28', 'xs:px-32', 'xs:px-36', 'xs:px-40', 'xs:px-44', 'xs:px-48', 'xs:px-52', 'xs:px-56'],
        ['sm:px-0', 'sm:px-0.5', 'sm:px-1', 'sm:px-2', 'sm:px-3', 'sm:px-4', 'sm:px-5', 'sm:px-6', 'sm:px-7', 'sm:px-8', 'sm:px-9', 'sm:px-10', 'sm:px-11', 'sm:px-12', 'sm:px-14', 'sm:px-16', 'sm:px-20', 'sm:px-24', 'sm:px-28', 'sm:px-32', 'sm:px-36', 'sm:px-40', 'sm:px-44', 'sm:px-48', 'sm:px-52', 'sm:px-56'],
        ['md:px-0', 'md:px-0.5', 'md:px-1', 'md:px-2', 'md:px-3', 'md:px-4', 'md:px-5', 'md:px-6', 'md:px-7', 'md:px-8', 'md:px-9', 'md:px-10', 'md:px-11', 'md:px-12', 'md:px-14', 'md:px-16', 'md:px-20', 'md:px-24', 'md:px-28', 'md:px-32', 'md:px-36', 'md:px-40', 'md:px-44', 'md:px-48', 'md:px-52', 'md:px-56'],
        ['lg:px-0', 'lg:px-0.5', 'lg:px-1', 'lg:px-2', 'lg:px-3', 'lg:px-4', 'lg:px-5', 'lg:px-6', 'lg:px-7', 'lg:px-8', 'lg:px-9', 'lg:px-10', 'lg:px-11', 'lg:px-12', 'lg:px-14', 'lg:px-16', 'lg:px-20', 'lg:px-24', 'lg:px-28', 'lg:px-32', 'lg:px-36', 'lg:px-40', 'lg:px-44', 'lg:px-48', 'lg:px-52', 'lg:px-56'],
        ['xl:px-0', 'xl:px-0.5', 'xl:px-1', 'xl:px-2', 'xl:px-3', 'xl:px-4', 'xl:px-5', 'xl:px-6', 'xl:px-7', 'xl:px-8', 'xl:px-9', 'xl:px-10', 'xl:px-11', 'xl:px-12', 'xl:px-14', 'xl:px-16', 'xl:px-20', 'xl:px-24', 'xl:px-28', 'xl:px-32', 'xl:px-36', 'xl:px-40', 'xl:px-44', 'xl:px-48', 'xl:px-52', 'xl:px-56'],

        ['py-0', 'py-0.5', 'py-1', 'py-2', 'py-3', 'py-4', 'py-5', 'py-6', 'py-7', 'py-8', 'py-9', 'py-10', 'py-11', 'py-12', 'py-14', 'py-16', 'py-20', 'py-24', 'py-28', 'py-32', 'py-36', 'py-40', 'py-44', 'py-48', 'py-52', 'py-56'],
        ['xs:py-0', 'xs:py-0.5', 'xs:py-1', 'xs:py-2', 'xs:py-3', 'xs:py-4', 'xs:py-5', 'xs:py-6', 'xs:py-7', 'xs:py-8', 'xs:py-9', 'xs:py-10', 'xs:py-11', 'xs:py-12', 'xs:py-14', 'xs:py-16', 'xs:py-20', 'xs:py-24', 'xs:py-28', 'xs:py-32', 'xs:py-36', 'xs:py-40', 'xs:py-44', 'xs:py-48', 'xs:py-52', 'xs:py-56'],
        ['sm:py-0', 'sm:py-0.5', 'sm:py-1', 'sm:py-2', 'sm:py-3', 'sm:py-4', 'sm:py-5', 'sm:py-6', 'sm:py-7', 'sm:py-8', 'sm:py-9', 'sm:py-10', 'sm:py-11', 'sm:py-12', 'sm:py-14', 'sm:py-16', 'sm:py-20', 'sm:py-24', 'sm:py-28', 'sm:py-32', 'sm:py-36', 'sm:py-40', 'sm:py-44', 'sm:py-48', 'sm:py-52', 'sm:py-56'],
        ['md:py-0', 'md:py-0.5', 'md:py-1', 'md:py-2', 'md:py-3', 'md:py-4', 'md:py-5', 'md:py-6', 'md:py-7', 'md:py-8', 'md:py-9', 'md:py-10', 'md:py-11', 'md:py-12', 'md:py-14', 'md:py-16', 'md:py-20', 'md:py-24', 'md:py-28', 'md:py-32', 'md:py-36', 'md:py-40', 'md:py-44', 'md:py-48', 'md:py-52', 'md:py-56'],
        ['lg:py-0', 'lg:py-0.5', 'lg:py-1', 'lg:py-2', 'lg:py-3', 'lg:py-4', 'lg:py-5', 'lg:py-6', 'lg:py-7', 'lg:py-8', 'lg:py-9', 'lg:py-10', 'lg:py-11', 'lg:py-12', 'lg:py-14', 'lg:py-16', 'lg:py-20', 'lg:py-24', 'lg:py-28', 'lg:py-32', 'lg:py-36', 'lg:py-40', 'lg:py-44', 'lg:py-48', 'lg:py-52', 'lg:py-56'],
        ['xl:py-0', 'xl:py-0.5', 'xl:py-1', 'xl:py-2', 'xl:py-3', 'xl:py-4', 'xl:py-5', 'xl:py-6', 'xl:py-7', 'xl:py-8', 'xl:py-9', 'xl:py-10', 'xl:py-11', 'xl:py-12', 'xl:py-14', 'xl:py-16', 'xl:py-20', 'xl:py-24', 'xl:py-28', 'xl:py-32', 'xl:py-36', 'xl:py-40', 'xl:py-44', 'xl:py-48', 'xl:py-52', 'xl:py-56'],

        ['m-0', 'm-0.5', 'm-1', 'm-2', 'm-3', 'm-4', 'm-5', 'm-6', 'm-7', 'm-8', 'm-9', 'm-10', 'm-11', 'm-12', 'm-14', 'm-16', 'm-20', 'm-24', 'm-28', 'm-32', 'm-36', 'm-40', 'm-44', 'm-48', 'm-52', 'm-56'],
        ['xs:m-0', 'xs:m-0.5', 'xs:m-1', 'xs:m-2', 'xs:m-3', 'xs:m-4', 'xs:m-5', 'xs:m-6', 'xs:m-7', 'xs:m-8', 'xs:m-9', 'xs:m-10', 'xs:m-11', 'xs:m-12', 'xs:m-14', 'xs:m-16', 'xs:m-20', 'xs:m-24', 'xs:m-28', 'xs:m-32', 'xs:m-36', 'xs:m-40', 'xs:m-44', 'xs:m-48', 'xs:m-52', 'xs:m-56'],
        ['sm:m-0', 'sm:m-0.5', 'sm:m-1', 'sm:m-2', 'sm:m-3', 'sm:m-4', 'sm:m-5', 'sm:m-6', 'sm:m-7', 'sm:m-8', 'sm:m-9', 'sm:m-10', 'sm:m-11', 'sm:m-12', 'sm:m-14', 'sm:m-16', 'sm:m-20', 'sm:m-24', 'sm:m-28', 'sm:m-32', 'sm:m-36', 'sm:m-40', 'sm:m-44', 'sm:m-48', 'sm:m-52', 'sm:m-56'],
        ['md:m-0', 'md:m-0.5', 'md:m-1', 'md:m-2', 'md:m-3', 'md:m-4', 'md:m-5', 'md:m-6', 'md:m-7', 'md:m-8', 'md:m-9', 'md:m-10', 'md:m-11', 'md:m-12', 'md:m-14', 'md:m-16', 'md:m-20', 'md:m-24', 'md:m-28', 'md:m-32', 'md:m-36', 'md:m-40', 'md:m-44', 'md:m-48', 'md:m-52', 'md:m-56'],
        ['lg:m-0', 'lg:m-0.5', 'lg:m-1', 'lg:m-2', 'lg:m-3', 'lg:m-4', 'lg:m-5', 'lg:m-6', 'lg:m-7', 'lg:m-8', 'lg:m-9', 'lg:m-10', 'lg:m-11', 'lg:m-12', 'lg:m-14', 'lg:m-16', 'lg:m-20', 'lg:m-24', 'lg:m-28', 'lg:m-32', 'lg:m-36', 'lg:m-40', 'lg:m-44', 'lg:m-48', 'lg:m-52', 'lg:m-56'],
        ['xl:m-0', 'xl:m-0.5', 'xl:m-1', 'xl:m-2', 'xl:m-3', 'xl:m-4', 'xl:m-5', 'xl:m-6', 'xl:m-7', 'xl:m-8', 'xl:m-9', 'xl:m-10', 'xl:m-11', 'xl:m-12', 'xl:m-14', 'xl:m-16', 'xl:m-20', 'xl:m-24', 'xl:m-28', 'xl:m-32', 'xl:m-36', 'xl:m-40', 'xl:m-44', 'xl:m-48', 'xl:m-52', 'xl:m-56'],

        ['mx-0', 'mx-0.5', 'mx-1', 'mx-2', 'mx-3', 'mx-4', 'mx-5', 'mx-6', 'mx-7', 'mx-8', 'mx-9', 'mx-10', 'mx-11', 'mx-12', 'mx-14', 'mx-16', 'mx-20', 'mx-24', 'mx-28', 'mx-32', 'mx-36', 'mx-40', 'mx-44', 'mx-48', 'mx-52', 'mx-56'],
        ['xs:mx-0', 'xs:mx-0.5', 'xs:mx-1', 'xs:mx-2', 'xs:mx-3', 'xs:mx-4', 'xs:mx-5', 'xs:mx-6', 'xs:mx-7', 'xs:mx-8', 'xs:mx-9', 'xs:mx-10', 'xs:mx-11', 'xs:mx-12', 'xs:mx-14', 'xs:mx-16', 'xs:mx-20', 'xs:mx-24', 'xs:mx-28', 'xs:mx-32', 'xs:mx-36', 'xs:mx-40', 'xs:mx-44', 'xs:mx-48', 'xs:mx-52', 'xs:mx-56'],
        ['sm:mx-0', 'sm:mx-0.5', 'sm:mx-1', 'sm:mx-2', 'sm:mx-3', 'sm:mx-4', 'sm:mx-5', 'sm:mx-6', 'sm:mx-7', 'sm:mx-8', 'sm:mx-9', 'sm:mx-10', 'sm:mx-11', 'sm:mx-12', 'sm:mx-14', 'sm:mx-16', 'sm:mx-20', 'sm:mx-24', 'sm:mx-28', 'sm:mx-32', 'sm:mx-36', 'sm:mx-40', 'sm:mx-44', 'sm:mx-48', 'sm:mx-52', 'sm:mx-56'],
        ['md:mx-0', 'md:mx-0.5', 'md:mx-1', 'md:mx-2', 'md:mx-3', 'md:mx-4', 'md:mx-5', 'md:mx-6', 'md:mx-7', 'md:mx-8', 'md:mx-9', 'md:mx-10', 'md:mx-11', 'md:mx-12', 'md:mx-14', 'md:mx-16', 'md:mx-20', 'md:mx-24', 'md:mx-28', 'md:mx-32', 'md:mx-36', 'md:mx-40', 'md:mx-44', 'md:mx-48', 'md:mx-52', 'md:mx-56'],
        ['lg:mx-0', 'lg:mx-0.5', 'lg:mx-1', 'lg:mx-2', 'lg:mx-3', 'lg:mx-4', 'lg:mx-5', 'lg:mx-6', 'lg:mx-7', 'lg:mx-8', 'lg:mx-9', 'lg:mx-10', 'lg:mx-11', 'lg:mx-12', 'lg:mx-14', 'lg:mx-16', 'lg:mx-20', 'lg:mx-24', 'lg:mx-28', 'lg:mx-32', 'lg:mx-36', 'lg:mx-40', 'lg:mx-44', 'lg:mx-48', 'lg:mx-52', 'lg:mx-56'],
        ['xl:mx-0', 'xl:mx-0.5', 'xl:mx-1', 'xl:mx-2', 'xl:mx-3', 'xl:mx-4', 'xl:mx-5', 'xl:mx-6', 'xl:mx-7', 'xl:mx-8', 'xl:mx-9', 'xl:mx-10', 'xl:mx-11', 'xl:mx-12', 'xl:mx-14', 'xl:mx-16', 'xl:mx-20', 'xl:mx-24', 'xl:mx-28', 'xl:mx-32', 'xl:mx-36', 'xl:mx-40', 'xl:mx-44', 'xl:mx-48', 'xl:mx-52', 'xl:mx-56'],

        ['my-0', 'my-0.5', 'my-1', 'my-2', 'my-3', 'my-4', 'my-5', 'my-6', 'my-7', 'my-8', 'my-9', 'my-10', 'my-11', 'my-12', 'my-14', 'my-16', 'my-20', 'my-24', 'my-28', 'my-32', 'my-36', 'my-40', 'my-44', 'my-48', 'my-52', 'my-56'],
        ['xs:my-0', 'xs:my-0.5', 'xs:my-1', 'xs:my-2', 'xs:my-3', 'xs:my-4', 'xs:my-5', 'xs:my-6', 'xs:my-7', 'xs:my-8', 'xs:my-9', 'xs:my-10', 'xs:my-11', 'xs:my-12', 'xs:my-14', 'xs:my-16', 'xs:my-20', 'xs:my-24', 'xs:my-28', 'xs:my-32', 'xs:my-36', 'xs:my-40', 'xs:my-44', 'xs:my-48', 'xs:my-52', 'xs:my-56'],
        ['sm:my-0', 'sm:my-0.5', 'sm:my-1', 'sm:my-2', 'sm:my-3', 'sm:my-4', 'sm:my-5', 'sm:my-6', 'sm:my-7', 'sm:my-8', 'sm:my-9', 'sm:my-10', 'sm:my-11', 'sm:my-12', 'sm:my-14', 'sm:my-16', 'sm:my-20', 'sm:my-24', 'sm:my-28', 'sm:my-32', 'sm:my-36', 'sm:my-40', 'sm:my-44', 'sm:my-48', 'sm:my-52', 'sm:my-56'],
        ['md:my-0', 'md:my-0.5', 'md:my-1', 'md:my-2', 'md:my-3', 'md:my-4', 'md:my-5', 'md:my-6', 'md:my-7', 'md:my-8', 'md:my-9', 'md:my-10', 'md:my-11', 'md:my-12', 'md:my-14', 'md:my-16', 'md:my-20', 'md:my-24', 'md:my-28', 'md:my-32', 'md:my-36', 'md:my-40', 'md:my-44', 'md:my-48', 'md:my-52', 'md:my-56'],
        ['lg:my-0', 'lg:my-0.5', 'lg:my-1', 'lg:my-2', 'lg:my-3', 'lg:my-4', 'lg:my-5', 'lg:my-6', 'lg:my-7', 'lg:my-8', 'lg:my-9', 'lg:my-10', 'lg:my-11', 'lg:my-12', 'lg:my-14', 'lg:my-16', 'lg:my-20', 'lg:my-24', 'lg:my-28', 'lg:my-32', 'lg:my-36', 'lg:my-40', 'lg:my-44', 'lg:my-48', 'lg:my-52', 'lg:my-56'],
        ['xl:my-0', 'xl:my-0.5', 'xl:my-1', 'xl:my-2', 'xl:my-3', 'xl:my-4', 'xl:my-5', 'xl:my-6', 'xl:my-7', 'xl:my-8', 'xl:my-9', 'xl:my-10', 'xl:my-11', 'xl:my-12', 'xl:my-14', 'xl:my-16', 'xl:my-20', 'xl:my-24', 'xl:my-28', 'xl:my-32', 'xl:my-36', 'xl:my-40', 'xl:my-44', 'xl:my-48', 'xl:my-52', 'xl:my-56'],

        ['flex-row', 'flex-col'],
        ['xs:flex-row', 'xs:flex-col'],
        ['sm:flex-row', 'sm:flex-col'],
        ['md:flex-row', 'md:flex-col'],
        ['lg:flex-row', 'lg:flex-col'],
        ['xl:flex-row', 'xl:flex-col'],

        ['min-w-fit', 'w-fit', 'w-full'],
        ['xs:min-w-fit', 'xs:w-fit', 'xs:w-full'],
        ['sm:min-w-fit', 'sm:w-fit', 'sm:w-full'],
        ['md:min-w-fit', 'md:w-fit', 'md:w-full'],
        ['lg:min-w-fit', 'lg:w-fit', 'lg:w-full'],
        ['xl:min-w-fit', 'xl:w-fit', 'xl:w-full'],

        ['min-h-fit', 'h-fit', 'h-full'],
        ['xs:min-h-fit', 'xs:h-fit', 'xs:h-full'],
        ['sm:min-h-fit', 'sm:h-fit', 'sm:h-full'],
        ['md:min-h-fit', 'md:h-fit', 'md:h-full'],
        ['lg:min-h-fit', 'lg:h-fit', 'lg:h-full'],
        ['xl:min-h-fit', 'xl:h-fit', 'xl:h-full'],

        ['overflow-visible', 'overflow-auto', 'overflow-hidden', 'overflow-scroll'],
    ];

    void defaultSafeList;
    // svelte-ignore state_referenced_locally
    void classList;
</script>
