/* cspell:disable */
const loremText: string =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat orci eget augue tincidunt, a fringilla tellus ultricies. Proin non ex id risus imperdiet posuere ut in odio. Suspendisse potenti. Proin ac aliquam quam, sed molestie quam. Fusce tincidunt nec ligula id dignissim. In nec laoreet lacus, ac eleifend velit. Donec egestas at dui in sollicitudin. Nunc non dolor accumsan, semper leo non, egestas ex. Nunc interdum sollicitudin lorem sed sagittis.' +
    'Proin lacinia tellus eu sem dictum, sit amet semper ex blandit. Suspendisse congue ullamcorper diam, et eleifend odio convallis accumsan. Fusce vitae enim mauris. Mauris iaculis imperdiet mauris in malesuada. Nam sit amet semper tellus. Curabitur venenatis sodales sapien, sit amet sollicitudin leo sodales bibendum. Donec sem augue, suscipit ac justo quis, eleifend finibus nunc. Pellentesque est nulla, ultrices id tincidunt at, porta eget odio. Cras sem nisl, finibus ac pretium vel, viverra in ante. Sed euismod vulputate nisl at accumsan.' +
    'Vivamus viverra, elit eget lobortis posuere, lacus tortor efficitur mauris, et porta lectus nisl a eros. Cras suscipit diam est, id lacinia orci molestie sed. Duis ac tempus est. Vestibulum commodo nisl quis porttitor fringilla. Fusce et suscipit justo. Fusce quis libero sed nunc gravida maximus eget id arcu. Sed scelerisque lorem ac turpis aliquet congue. Nullam luctus congue dapibus. Maecenas elementum placerat felis eu lobortis. Proin turpis sapien, porta eu odio id, imperdiet pharetra enim. Nam luctus rhoncus nisl, non fringilla lacus sollicitudin ut. Fusce auctor ante non iaculis consequat. Integer suscipit quis nibh non sollicitudin. Curabitur et ex eu ante pellentesque euismod ac sed metus.' +
    'Vivamus sodales justo quis ornare gravida. Praesent tincidunt tortor sit amet metus facilisis, sed gravida justo sollicitudin. Maecenas enim sapien, dictum ac dapibus et, lacinia non magna. In id purus dolor. Nam lacinia finibus lacus, sit amet elementum mauris imperdiet in. Integer vestibulum purus ultricies, dignissim risus non, vehicula sapien. Proin bibendum, urna ac vulputate convallis, ex erat sodales ante, quis vulputate quam turpis non turpis. Sed ac tellus id lacus hendrerit placerat. Sed laoreet luctus urna, ultrices lobortis nibh condimentum a. Donec at vehicula ipsum, ut dignissim purus.' +
    'Nam ultrices, justo vel lacinia viverra, quam nisl viverra libero, ac ullamcorper tellus sem eget mauris. Morbi eu faucibus lorem, vel faucibus ligula. Nam arcu mauris, blandit quis hendrerit ut, malesuada et nisl. Aenean sit amet dui eget orci dapibus porttitor eget eu ligula. Praesent sed nulla risus. Cras euismod turpis quis turpis tempor aliquet. Phasellus efficitur sem varius magna sodales viverra. Quisque cursus arcu a nunc laoreet hendrerit. Vivamus hendrerit ante tortor, eget faucibus tortor malesuada vel. Nunc sit amet commodo turpis, sit amet ultricies mauris.';
/* cspell:enable */

export const lorem = {
    short: loremText.slice(0, 56),
    medium: loremText.slice(0, 250),
    long: loremText
};
