minimumReleaseAge: 10080
trustPolicy: no-downgrade
blockExoticSubdeps: true
onlyBuiltDependencies:
    - msw
    - workerd
ignoredBuiltDependencies:
    - esbuild
    - sharp
overrides:
    chokidar@4.0.3: ^5.0.0
allowBuilds:
    esbuild: false
    msw: true
    sharp: false
    workerd: true
