// fix the generated svg parser by prepending it with comments to disable eslint, typescript and svelte checking
import fs from 'fs';
import path from 'path';

const comments = [
    '////// DO NOT EDIT THIS FILE //////',
    '',
    '// Based on : https://raw.githubusercontent.com/hughsk/svg-path-parser/refs/heads/master/grammar.peg',
    '',
    '/* eslint-disable */',
    '// @ts-nocheck',
    ''
];

const parserPath = path.resolve('src/components/atoms/svg/_parser.js');
const parser = fs.readFileSync(parserPath, 'utf8');
const fixedParser = comments.join('\n') + '\n' + parser;
fs.writeFileSync(parserPath, fixedParser);
